site_name: Mobile Action Kit Documentation
nav:
  - MOBILE ACTION KIT:
    - Player:
       - Player Setup: PlayerSetup.md
       - Minimap Setup: PlayerMiniMapSetup.md
       - Player Health: PlayerHealthSetup.md
       - Footstep Sounds Based On Surfaces: PlayerFootstepSoundsBasedOnSurfaces.md
       - PlayerWeaponSetup Part-1: PlayerWeaponSetup_Part1.md
       - PlayerWeaponBobbing,Recoil&Crosshair Part-2: PlayerWeaponSetupBobbing,Recoil&Crosshair_Part2.md
       - PlayerWeaponShootingFeatures Part-3: PlayerWeaponShootingFeatures_Part3.md
       - PlayerWeaponProjectileShooting Part-4: PlayerWeaponProjectileShooting_Part4.md 
    - Humanoid Soldier AI:
       - Getting Started: HumanoidAiGetStarted.md
       - Setting Up The Agent: HumanoidAiSettingUpAgent.md
       - AI Agent Tactical Interactions: HumanoidAITacticalInteractions.md
       - Head Rotation Behaviour: HumanoidAIHeadRotation.md
       - Stationed & Scanning Behaviour: HumanoidAIScanningBehaviour.md
       - Wander Behaviour: HumanoidAIWanderBehaviour.md
       - Patrol Behaviour: HumanoidAIPatrolBehaviour.md
       - Stationed Shoot Posture Behaviour: HumanoidAIStationedShootPosture.md
       - Agent Health : HumanoidAIHealth.md
       - Pursue Behaviour : HumanoidAIPursue.md
       - Post Combat Scan : HumanoidAIPostCombatScan.md
       - Strafing : HumanoidAIStrafing.md
       - Charging Behaviour : HumanoidAICharging.md
       - Humanoid Body Hits : HumanoidAIBodyHits.md
       - Melee Attacks : HumanoidAIMelee.md
       - Weapon Firing Behaviour Part-1 : HumanoidAIWeaponFiringBehaviour_Part1.md 
       - Weapon Firing Behaviour Part-2 : HumanoidAIWeaponFiringBehaviour_Part2.md 
       - Weapon Firing Behaviour Part-3 : HumanoidAIWeaponFiringBehaviour_Part3.md 
       - Weapon Firing Behaviour Part-4 : HumanoidAIWeaponFiringBehaviour_Part4.md 
       - Weapon Firing Behaviour Part-5 : HumanoidAIWeaponFiringBehaviour_Part5.md 
       - Firing Points Part-1 : AIFiringPoint_Part1.md 
       - Firing Points Part-2 : AIFiringPoint_Part2.md 
       - Crouch Hiding Cover Part-1 : AI_CrouchHidingCover.md 
       - Crouch Firing Cover Part-2 : AI_CrouchFiringCover.md 
       - Stand Hiding Cover Part-3 : AI_StandFiringCover.md 
       - Stand Firing Cover Part-4 : AI_StandHidingCover.md 
       - Covers Fields Explanation Part-5 : AI_Covers_Explanation.md 
       - Grenade Setup Part-1 : AI_GrenadeSetup.md
       - Grenade Throw Part-2 : AI_GrenadeThrow.md
       - Grenade Alerts Part-3 : AI_GrenadeAlerts.md
       - Grenade No Throw Area Part-4 : AI_GrenadeNoThrowArea.md
       - Leader & Followers Part-1 : AILeader&Follower_Part1.md
       - Leader & Followers Part-2 : AILeader&Follower_Part2.md
       - Player Leader & AI Followers Part-3 : PlayerLeader&Follower_Part3.md
       - Emergency State (Zig Zag Advancing) Part-1 : AIEmergencyState_ZigZagAdvancing_Part1.md
       - Emergency State (Advancing Between Covers) Part-2 : AIEmergencyState_AdvancingBetweenCovers_Part2.md
       - Emergency State (Emergency Shooting) Part-3 : AIEmergencyState_EmergencyShooting_Part3.md
       - Emergency State (Fleeing Behaviour) Part-4 : AIEmergencyState_AIFleeingBehaviour_Part4.md
       - Emergency State (Friendly Chain Reaction) Part-5 : AIEmergencyState_FriendlyChainReaction_Part5.md
       - Emergency State (Friendly Death & Pavement Effect Emergency) Part-6 : AIEmergencyState_FriendlyDeath&PavementEffectEmergency_Part6.md
       - Emergency State (Other Scenarios) Part-7 : AIEmergencyState_OtherScenarios_Part7.md
       - DeadBody Investigation : AIInvestigationNearTheDeadBody.md
       - FootStep Sounds Part-1 : AIFootstepSounds.md
       - Recurring & Non Recurring Sounds Part-2 : AIRecurringAndNonRecurringSounds.md
       - Non Combat Chatter Part-3 : AINonCombatChatter.md
       - Sound Alert Behaviour Part-4 : AISoundAlertBehaviour_Part1.md
       - Sound Alert Behaviour Part-5 : AISoundAlertBehaviour_Part2.md
       - Sound Investigation & Emergency Behaviour Part-6 : AISoundInvestigation&EmergencyBehaviour.md
       - Master AI Agent : MasterAIAgent.md
       - Simple Spawner : SimpleSpawner.md
       - AI Maintaining Spawner : AIMaintainingSpawner.md
       - Wave Spawner : WaveSpawner.md
       - Merge Wave Spawner & AI Maintaining Spawner : MergeWaveSpawner&AIMaintainingSpawner.md
       - Making Pistol Shooter AI Agent : MakingPistolShooter_AIAgent.md
    - Humanoid Zombie AI:
       - Getting Started: ZombieHumanoidAiGetStarted.md
       - Head Rotation Behaviour: HumanoidAIZombieHeadRotation.md
       - Scanning Behaviour: HumanoidAIZombieScanningBehaviour.md
       - Wander Behaviour: HumanoidAIZombieWanderBehaviour.md
       - Patrol Behaviour: HumanoidAIZombiePatrolBehaviour.md
       - Charging & Melee Attack Behaviour : HumanoidAIZombieCharging&Melee.md
       - Zombie Body Hits : ZombieBodyHits.md
       - Pursue behaviour : ZombiePursue.md
       - Health : ZombieHealth.md
       - FootStep Sounds : ZombieFootstepSounds.md
       - Setting up Zombie Voices : ZombieVoices.md
       - Sound Alerts : ZombieSoundAlerts.md
    - Shop: Shop.md
  # - HELICOPTER:
  #   - Basic Setup:
  #      - Animation: Helibase.md
  #      - Collider: Helibase.md
  - SUPPORT: Support.md
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  logo: Images/Logo.png
  favicon: Images/Logo.png
  custom_dir: docs/overrides
  nav_style: default
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.code
    - prev_next_buttons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep blue
      accent:  black
plugins:
  - search
extra_css:
  - overrides/extra.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://github.com/james-willett  
    - icon: fontawesome/solid/envelope
      link: https://github.com/james-willett  
copyright: |
   &copy; 2024<a href="https://github.com/MobileActionKit" target="_blank" rel="noopener">MobileActionKit</a>