site_name: DOCUMENTATION
nav:
  - MOBILE ACTION KIT:
    - Player:
       - SettingUpPlayer: Index.md
       - SettingUpWeapon: AISystem.md
    - Humanoid AI:
       - Setting Up Ragdoll: Index.md
       - Covers: Index.md
    - Shop: Shop.md
  - HELICOPTER:
    - Basic Setup:
       - Animation: Helibase.md
       - Collider: AISystem.md
  - SUPPORT: Support.md
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  logo: Images/screen.png
  favicon: Images/screen.png
  custom_dir: docs/overrides
  nav_style: default
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.code
    - prev_next_buttons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: red
      accent: red
plugins:
  - search
extra_css:
  - overrides/extra.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://github.com/james-willett  
    - icon: fontawesome/solid/envelope
      link: https://github.com/james-willett  
copyright: |
   &copy; 2024<a href="https://github.com/MobileActionKit" target="_blank" rel="noopener">MobileActionKit</a>      

