site_name: Mobile Action Kit Documentation
nav:
  - MOBILE ACTION KIT:
    - Player:
       - SettingUpPlayer: HumanoidAiGetStarted.md
       - SettingUpWeapon: AISystem.md
    - Humanoid AI:
       - Getting Started: HumanoidAiGetStarted.md
       - Setting Up The Agent: HumanoidAiSettingUpAgent.md
       - AI Agent Tactical Interactions: HumanoidAITacticalInteractions.md
       - Head Rotation Behaviour: HumanoidAIHeadRotation.md
       - Stationed & Scanning Behaviour: HumanoidAIScanningBehaviour.md
       - Wander Behaviour: HumanoidAIWanderBehaviour.md
       - Patrol Behaviour: HumanoidAIPatrolBehaviour.md
       - Stationed Shoot Posture Behaviour: HumanoidAIStationedShootPosture.md
       - Agent Health : HumanoidAIHealth.md
       - Pursue Behaviour : HumanoidAIPursue.md
       - Post Combat Scan : HumanoidAIPostCombatScan.md
       - Strafing : HumanoidAIStrafing.md
       - Charging Behaviour : HumanoidAICharging.md
       - Humanoid Body Hits : HumanoidAIBodyHits.md
       - Melee Attacks : HumanoidAIMelee.md
       - Weapon Firing Behaviour Part-1 : HumanoidAIWeaponFiringBehaviour_Part1.md 
       - Weapon Firing Behaviour Part-2 : HumanoidAIWeaponFiringBehaviour_Part2.md 
       - Weapon Firing Behaviour Part-3 : HumanoidAIWeaponFiringBehaviour_Part3.md 
       - Weapon Firing Behaviour Part-4 : HumanoidAIWeaponFiringBehaviour_Part4.md 
       - Weapon Firing Behaviour Part-5 : HumanoidAIWeaponFiringBehaviour_Part5.md 
       - AI Firing Points Part-1 : AIFiringPoint_Part1.md 
       - AI Firing Points Part-2 : AIFiringPoint_Part2.md 
       - AI Crouch Hiding Cover Part-1 : AI_CrouchHidingCover.md 
       - AI Crouch Firing Cover Part-2 : AI_CrouchFiringCover.md 
       - AI Stand Hiding Cover Part-3 : AI_StandFiringCover.md 
       - AI Stand Firing Cover Part-4 : AI_StandHidingCover.md 
       - AI Covers Fields Explanation Part-5 : AI_Covers_Explanation.md 
       - AI Grenade Setup Part-1 : AI_GrenadeSetup.md
       - AI Grenade Throw Part-2 : AI_GrenadeThrow.md
       - AI Grenade Alerts Part-3 : AI_GrenadeAlerts.md
       - AI Grenade No Throw Area Part-4 : AI_GrenadeNoThrowArea.md
       - AI Leader & Followers Part-1 : AILeader&Follower_Part1.md
       - AI Leader & Followers Part-2 : AILeader&Follower_Part2.md
       - Player Leader & AI Followers Part-3 : PlayerLeader&Follower_Part3.md
       - AI Emergency State (Zig Zag Advancing) Part-1 : AIEmergencyState_ZigZagAdvancing_Part1.md
       - AI Emergency State (Advancing Between Covers) Part-2 : AIEmergencyState_AdvancingBetweenCovers_Part2.md
       - AI Emergency State (Emergency Shooting) Part-3 : AIEmergencyState_EmergencyShooting_Part3.md
       - AI Emergency State (Fleeing Behaviour) Part-4 : AIEmergencyState_AIFleeingBehaviour_Part4.md
    - Shop: Shop.md
  # - HELICOPTER:
  #   - Basic Setup:
  #      - Animation: Helibase.md
  #      - Collider: Helibase.md
  - SUPPORT: Support.md
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  logo: Images/Logo.png
  favicon: Images/Logo.png
  custom_dir: docs/overrides
  nav_style: default
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.code
    - prev_next_buttons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep blue
      accent:  black
plugins:
  - search
extra_css:
  - overrides/extra.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://github.com/james-willett  
    - icon: fontawesome/solid/envelope
      link: https://github.com/james-willett  
copyright: |
   &copy; 2024<a href="https://github.com/MobileActionKit" target="_blank" rel="noopener">MobileActionKit</a>